spring:
  datasource:
    driver-class-name: org.h2.Driver
    #username: sa
    #password:
    
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: true
    database: h2
    show-sql: true
    

logging.level:
  org.hibernate.SQL: debug

security:
  jwt:
    token:
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds